title: aicgen
description: AI Config Generator for Coding Assistants
baseurl: ""
url: "https://aicgen.github.io"

markdown: kramdown
theme: null

exclude:
  - node_modules
  - package.json
  - yarn.lock
  - vite.config.ts
  - tsconfig.json
  - README.md
  - components
  - App.tsx
  - index.tsx
  - types.ts
  - .env.local
  - dist
